services:
  almanotesimport:
    build: .
    container_name: almanotesimport
    environment:
      DATABASE: "mysql+pymysql://user:password@almanotesimport_db:3306/mydb"
      SECRET_APP_KEY: '!secret!'
      SHARED_SECRET: '1*HXgRn9qJK5BmgeiMu%q3UF'
      LOG_DIR: 'app/log'
      LOG_LEVEL: 'DEBUG'
      ALMA_SERVER: 'https://api-na.hosted.exlibrisgroup.com'
      SMTP_ADDRESS: 'host.docker.internal:8025'
      SENDER_EMAIL: 'almanotesimport@wrlc.org'
      SITE_URL: 'https://almanotesimport.wrlc.localhost'
      SAML_SP: 'https://simplesamlphp.wrlc.localhost'
      COOKIE_ISSUING_FILE: '/login'
      LOGOUT_SCRIPT: '/logout'
      COOKIE_PREFIX: '_wr_'
      SERVICE_SLUG: 'alma_notes_import'
      MEMCACHED_SERVER: 'aladinsp-memcached'
      INSTITUTION_CODE: 'wr'
      UPLOAD_FOLDER: 'app/static/csv'
    volumes:
      - .:/app
    working_dir: /app
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.almanotesimport.rule=Host(`almanotesimport.wrlc.localhost`)"
      - "traefik.http.routers.almanotesimport.tls=true"
      - "traefik.http.routers.almanotesimport.entrypoints=websecure"
    secrets:
      - ssh_key
      - gitconfig
    depends_on:
      - almanotesimport_db
    networks:
      - proxy

  almanotesimport_db:
    image: mariadb:latest
    container_name: almanotesimport_db
    environment:
      MARIADB_ROOT_PASSWORD: root
      MYSQL_DATABASE: mydb
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3323:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - proxy

secrets:
  ssh_key:
    file: ${SSH_KEY_FILE}
  gitconfig:
    file: ${GITCONFIG}

volumes:
    mysql-data:

networks:
  proxy:
    external: true
