services:
  almanotesimport:
    build: .
    volumes:
      - .:/app
    working_dir: /app
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.almanotesimport.rule=Host(`almanotesimport.wrlc.localhost`)"
      - "traefik.http.routers.almanotesimport.tls=true"
      - "traefik.http.routers.almanotesimport.entrypoints=websecure"
    networks:
      - proxy

  almanotesimport_db:
    image: mariadb:latest
    environment:
      MARIADB_ROOT_PASSWORD: root
      MYSQL_DATABASE: mydb
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    volumes:
      - mysql-data:/var/lib/mysql
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.almanotesimport_db.rule=Host(`db.almanotesimport.wrlc.localhost`)"
      - "traefik.tcp.services.almanotesimport_db.loadbalancer.server.port=3306"
      - "traefik.http.routers.almanotesimport_db.entrypoints=mysql"
    networks:
      - proxy

volumes:
    mysql-data:

networks:
  proxy:
    external: true
